# Generated by Django 5.2.4 on 2026-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouplicense",
            name="is_file_based",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grouplicense",
            name="is_row_based",
            field=models.BooleanField(default=False),
        ),
    ]
