# Generated by Django 5.2.4 on 2026-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_grouplicense_is_file_based_grouplicense_is_row_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouplicense",
            name="rows_per_credit",
            field=models.PositiveIntegerField(
                default=500, help_text="Number of rows that count as 1 credit"
            ),
        ),
    ]
