# Generated by Django 5.2.4 on 2026-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_grouplicense_rows_per_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplicense",
            name="rows_per_credit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of rows that count as 1 credit. Empty for File Based.",
                null=True,
            ),
        ),
    ]
